### ISSUE TITLE
Installing the Flux operator using Flux

### ISSUE THREAD

**Issue by chrede88** [controlplaneio-fluxcd/flux-operator#108]
I'm very much interested in moving my cluster to the Flux operator. It seems like such a cool project.

Can I install the operator by creating a "normal" flux helmrelease (`helm.toolkit.fluxcd.io/v2`) and a `FluxInstance` manifest and let Flux create the resources on my cluster? This way I can keep the manifest in the git repo and let Renovate look for upgrades for the operator.

From the [migration guide](https://fluxcd.control-plane.io/operator/flux-bootstrap-migration/) it sounds like this should be possible, as the operator and the `FluxInstance` will be present on this cluster simultaneously with the old flux resources, using the more manual `helm install` approach.

A potential issue would be how the operator will handle upgrades to itself!

**Comment by stefanprodan** [comment]
If at cluster creation you deploy the operator with the Helm CLI, after creating the `FluxInstance` on the cluster, you can add a HelmRelease to the repo and make use of Flux to upgrade the operator like so:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 10m
  url: ci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
  ref:
    semver: '*'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 10m
  releaseName: flux-operator
  chartRef:
    kind: OCIRepository
    name: flux-operator
```

If you are using [Terraform](https://github.com/controlplaneio-fluxcd/flux-operator/tree/main/config/terraform) to create the cluster and deploy the operator, you could use Renovate to bump the operator chart in Terraform and rerun it.
