### ISSUE TITLE
Pull Flux operator chart failed - failed to authorize

### ISSUE THREAD

**Issue by chrede88** [controlplaneio-fluxcd/flux-operator#109]
I'm trying to deploy the Flux operator, but I get a 403 error when trying to pull the helm chart.

Error:
```
source-controller  chart pull error: failed to download chart for remote reference: failed to get 'oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator/flux-operator:0.10.0': failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%!A(MISSING)controlplaneio-fluxcd%!F(MISSING)charts%!F(MISSING)flux-operator%!F(MISSING)flux-operator%!A(MISSING)pull&service=ghcr.io: 403 Forbidden
```

I've defined the following flux resources used to install the Flux operator.
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  type: oci
  interval: 2h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: flux-operator
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: flux-operator
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    serviceMonitor:
      create: true
```
