### ISSUE TITLE
Foreign labels are removed from flux-system namespace when deploying a flux-instance resource

### ISSUE THREAD

**Issue by sestegra** [controlplaneio-fluxcd/flux-operator#118]
- Create the flux-system namespace
```shell
$ kubectl create ns flux-system
$ kubectl label ns flux-system my-label=value
$ kubectl get ns flux-system -o jsonpath='{.metadata.labels}' | jq
{
  "kubernetes.io/metadata.name": "flux-system",
  "my-label": "value"
}
```
- Install the flux-operator (version v0.10.0) with the Helm Chart
```shell
$ helm install flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator \
  --namespace flux-system
```
- Create a flux-instance
```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.4.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
  cluster:
    type: kubernetes
```
- Install the flux-instance
``` shell
$ kubectl apply -f flux-instance.yaml
```

As a result, the foreign label has been removed.
```shell
$ kubectl get ns flux-system -o jsonpath='{.metadata.labels}' | jq
{
  "app.kubernetes.io/instance": "flux-system",
  "app.kubernetes.io/managed-by": "flux-operator",
  "app.kubernetes.io/part-of": "flux",
  "app.kubernetes.io/version": "v2.4.0",
  "fluxcd.controlplane.io/name": "flux",
  "fluxcd.controlplane.io/namespace": "flux-system",
  "kubernetes.io/metadata.name": "flux-system",
  "pod-security.kubernetes.io/warn": "restricted",
  "pod-security.kubernetes.io/warn-version": "latest"
}
```

**Comment by stefanprodan** [comment]
This is the expected behaviour, by design Flux removes all changes made with kubectl for managed resources. 

You have two options to solve this:

1. Add the labels to the FluxInstance

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
spec:
  kustomize:
    patches:
      - patch: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: flux-system
            labels:
               custom: custom
        target:
          kind: Namespace
```

Docs: https://fluxcd.control-plane.io/operator/flux-kustomize/

2. Add the labels manually using kubectl

```
kubectl label ns flux-system my-label=value --field-manager=flux-client-side-apply
```

Docs: https://fluxcd.io/flux/faq/#why-are-kubectl-edits-rolled-back-by-flux
