### ISSUE TITLE
Question: How to deal with existing flux installations

### ISSUE THREAD

**Issue by esteban1983cl** [controlplaneio-fluxcd/flux-operator#133]
Hi team, please help with this question:

I want use this controller, currently I have an EKS running flux, this was bootstrapped with flux cli.
How can you recommend deploy the FluxInstance manifest to manage an existing repository without enter in update loops ?
I my head pass a some things if I deploy a flux instance like this:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileArtifactEvery: "10m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  sync:
    kind: GitRepository
    url: "https://github.com/my-org/my-fleet.git"
    ref: "refs/heads/main"
    path: "clusters/my-cluster"
    pullSecret: "flux-system"
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  cluster:
    type: kubernetes
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  kustomize:
    patches:
      - target:
          kind: Deployment
          name: "(kustomize-controller|helm-controller)"
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=10
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --requeue-dependency=5s
```

Currently this repo has the gotk-sync.yaml and gotk-components.yaml that deploy flux with its components and the initial gitrepository and kustomization. What happen with that files ?

Thanks for your help
