### ISSUE TITLE
`ResourceSet` dynamic inputs from Git branches

### ISSUE THREAD

**Issue by stefanprodan** [controlplaneio-fluxcd/flux-operator#141]
This proposal is an extension of #140 that caters to a slightly diffrent use-case where instead of deploying from Pull Requests, we setup a workflow for deploying app instances from long-lived feature branches. To accommodate this use-case, the `ResourceSetInputProvider` should allow querying the Git service and return `ResourceSet` inputs for each branch found in a Git repository that matches a regex expression.

## Example

We'll use GitHub and the `podinfo` demo app to demonstrate how the new API should work, but the `ResourceSetInputProvider` could support GitLab, Azure DevOps, Gitea and any other Git service to list branches.

### Branch preview environments workflow

- A developer creates a feature branch named `feature/x` with code changes to the podinfo source code and to the Kubernetes YAMLs
- The CI builds the new app container image and pushes a tag to GHCR with the Git commit SHA
- Flux Operator running in the preview cluster scans the repository and finds the new branch using the branch regex filter
- Flux Operator creates a dedicated namespace for the feature branch where it deploys the app and patches the Kubernetes manifests to set the image tag to the commit SHA and the branch name as the Ingress host prefix
- The developers iterate over changes, with each push to the feature branch triggering an app deployment rollout in the cluster
- Once the brach is merged into main and deleted, the Flux Operator removes the namespace and app deployment form the cluster

### Flux Operator Config

To enable the above workflow, we'll define a series of Flux Operator custom resources in the preview cluster.

First we'll create a dedicated namespace called `apps-deploy` where all the Flux custom resources will reside. In that namespace, we'll create a Kubernetes Secret containing a GitHub token that grants read access to the podinfo repository.

In the `apps-deploy` namespace, we'll create a `ResourceSetInputProvider` that tells Flux Operator to scan the repository for branches matching the `^feature/.*` regex:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: podinfo-branches
  namespace: apps-deploy
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "10m"
spec:
  type: GitHubBranch
  url: https://github.com/stefanprodan/podinfo
  secretRef:
    name: podinfo-github-token
  filter:
    includeBranch: "^feature/.*"
```

To not wait 10 minutes for the operator to detect changes in the repo, we can trigger the scan by creating a Flux `Receiver` for GitHub to call:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-receiver
  namespace: apps-deploy
spec:
  type: github
  secretRef:
    name: receiver-token
  events:
    - "push"
  resources:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: podinfo-branches
```

Finally, to deploy podinfo from feature branches we'll create a `ResouceSet` that takes its inputs from the `ResourceSetInputProvider`:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: podinfo
  namespace: apps-deploy
spec:
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: podinfo-branches
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: podinfo-<< inputs.branch | slugify >>
        namespace: apps-deploy
      spec:
        interval: 1h
        url: https://github.com/stefanprodan/podinfo
        ref:
          branch: << inputs.branch >>
          commit: << inputs.sha >>
        secretRef:
          name: podinfo-github-token
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: podinfo-<< inputs.branch | slugify >>
        namespace: apps-deploy
        annotations:
          event.toolkit.fluxcd.io/preview-url: "https://podinfo-<< inputs.branch | slugify >>.example.com"
      spec:
        interval: 1h
        serviceAccountName: flux-restricted
        targetNamespace: podinfo-<< inputs.branch | slugify >>
        sourceRef:
          kind: GitRepository
          name: podinfo-<< inputs.branch | slugify >>
        path: deploy/kubernetes
        prune: true
        wait: true
        images:
          - name: ghcr.io/stefanprodan/podinfo
            newTag: << inputs.sha >>
        patches:
          - target:
              kind: Ingress
            patch: |
              - op: replace
                path: /spec/rules/0/host
                value: podinfo-<< inputs.branch | slugify >>.example.com
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: podinfo-<< inputs.branch | slugify >>
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: flux-restricted
        namespace: podinfo-<< inputs.branch | slugify >>
      subjects:
        - kind: ServiceAccount
          name: flux-restricted
          namespace: apps-deploy
          roleRef:
            kind: ClusterRole
            name: admin
            apiGroup: rbac.authorization.k8s.io
```

The above `ResouceSet` will generate a Kubernetes namespace, role binding, a Flux `GitRepository` and `Kustomization` for each Git branch. The branch name passed as `<< inputs.branch >>` is used for the namespace and as the name suffix for the Flux objects, and is also used to compose the Ingress host name where the app can be accessed. The latest commit SHA pushed to the branch HEAD is passed as `<< inputs.sha >>`, the SHA is used to set the app image tag. The preview URL is set in annotations on the Kustomization object to enrich the Flux notifications that the dev team receives.

To receive notifications when an application has been rolled out (including any deploy errors), a Flux `Alert` can be created in the `apps-deploy` namespace:

```yaml
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack-bot
  namespace: apps-deploy
spec:
  type: slack
  channel: general
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: slack-bot-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: slack
  namespace: apps-deploy
spec:
  providerRef:
    name: slack-bot
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
  eventMetadata:
    cluster: "preview-cluster-1"
    region: "us-east-1"
```

Note that all the Kubernetes manifests part of this workflow should be stored in the Git repository used to define the preview cluster desired state.

**Comment by matheuscscp** [comment]
> long-lived feature branches

Or long-lived environment branches.

**Comment by stefanprodan** [comment]
For environment branches when Flux runs in the [hub-and-spoke](https://github.com/fluxcd/flux2-hub-spoke-example) mode, the `ResourceSet` should deploy changes to remote clusters.

## Example

Assuming there is a GitLab project called `apps-deploy` with a branch per environment e.g. `env/staging` and `env/production`. Flux Operator running on the management cluster should deploy in the staging cluster from `env/staging` and in the production cluster from  `env/production`.

### Flux Operator Config

In the management cluster where Flux Operator is running, we'll create a `ResourceSetInputProvider` that scans the GitLab project for branches matching the ^env/.* regex:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: apps-envs
  namespace: apps-deploy
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "10m"
spec:
  type: GitLabBranch
  url: https://gitlab.com/my-org/apps-deploy
  secretRef:
    name: apps-gitlab-token
  filter:
    includeBranch: "^env/.*"
```

In the same namespace we'll create a `ResourceSet` that takes inputs for the provider and configures the `kubeConfig` and deploys the apps to the target clusters:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps
  namespace: apps-deploy
spec:
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: apps-envs
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: apps-<< inputs.branch | slugify >>
        namespace: apps-deploy
      spec:
        interval: 1h
        url: https://gitlab.com/my-org/apps-deploy
        ref:
          branch: << inputs.branch >>
          commit: << inputs.sha >>
        secretRef:
          name: apps-gitlab-token
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: apps-<< inputs.branch | slugify >>
        namespace: apps-deploy
      spec:
        interval: 1h
        sourceRef:
          kind: GitRepository
          name: apps-<< inputs.branch | slugify >>
        path: deploy/kubernetes
        prune: true
        kubeConfig:
          secretRef:
            name: << inputs.branch | slugify >>-kubeconfig
```

In the `apps-deploy` namespace the following Kubernetes secrets should exist:
- `apps-gitlab-token` - contains the GitLab PAT with read-only access to the `apps-deploy` project
- `env-staging-kubeconfig` - contains the kubeconfig for connecting to the staging cluster
- `env-production-kubeconfig` - contains the kubeconfig for connecting to the production cluster
