### ISSUE TITLE
`ResourceSet` time-based deploy window for Git branches

### ISSUE THREAD

**Issue by stefanprodan** [controlplaneio-fluxcd/flux-operator#148]
This proposal is an extension of #141 where instead of scanning Git branches for the latest commit continuously, we want to deploy changes from Git to the production clusters within a predefined time window. This caters to use-cases such as: maintenance windows, planned releases, No Deploy Friday.

## Example

Assuming we want to deploy changes to production every weekday from Monday to Thursday between 9:00 AM and 11:00 AM London time.

### Flux Operator Config

We can define a `ResourceSetInputProvider` that resolves the latest commit pushed to the `main` branch in the GitHub repository from where Flux reconciles apps to the production cluster with a `.spec.schedule`:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: apps-main-branch
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
  schedule:
  - cron: 0 9 * * 1-4
    timeZone: Europe/London
    window: 2h
  type: GitHubBranch # can be GitLabBranch
  url: https://github.com/my-org/my-apps-repo
  secretRef:
    name: gh-token-apps
  filter:
    includeBranch: "^main$"
```

This provider will export a single set of inputs that contains the latest commit SHA of the main branch:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: apps-main-branch
  namespace: flux-system
status:
  exportedInputs:
  - id: "1433470881"
    branch: "main"
    sha: "2dd3a8d2088457e5cf991018edf13e25cbd61380"
```

Outside of the schedule window, the exported inputs will remain unchanged, the SHA will be updated to the latest main HEAD only within the schedule window. If a GitHub/GitLab webhook is setup to trigger the provider, the webhook call will be ignored if it's outside the schedule window. 

To trigger a scan outside the schedule, users can annotate the `ResourceSetInputProvider` with
`reconcile.fluxcd.io/forceAt: "<current timestamp>"` and Flux Operator will reconcile only once then pause.

To deploy the apps, we can define a `ResourceSet` that pins the Flux `GitRepository` to the the commit SHA exported by the provider:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: apps
  namespace: flux-system
spec:
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: apps-main-branch
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: apps
        namespace: flux-system
      spec:
        interval: 1h
        url: https://github.com/my-org/my-apps-repo
        ref:
          branch: << inputs.branch >>
          commit: << inputs.sha >>
        secretRef:
          name: gh-token-apps
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: apps
        namespace: flux-system
      spec:
        interval: 1h
        retryInterval: 5m
        sourceRef:
          kind: GitRepository
          name: apps
        path: overlays/production
        prune: true
```

Note the `GitRepository` interval has no relevance as we pin the `.spec.ref.commit` to the SHA exported by the provider, so no matter the interval, Flux source-controller will checkout the same commit until the `ResourceSetInputProvider` schedule runs.

When a new commit is found by the `ResourceSetInputProvider` reconciler, both the `GitRepository` and the Flux `Kustomization` will be triggered by `ResourceSet` and Flux will deploy the latest changes from the production overlay.
