### ISSUE TITLE
Custom input values for RSIP

### ISSUE THREAD

**Issue by bo0tzz** [controlplaneio-fluxcd/flux-operator#167]
The new ResourceSetInputProvider functionality is awesome, and exactly what I've been looking for for a while now, thank you!

We occasionally want to create these environments with different parameters, e.g. whether to initialize a database from scratch or from a pre-populated snapshot. I think it would be very useful to have a way to pass custom inputs from the provider (eg as extra metadata on a pull request) to be used in the templating.

For the moment our current usecase can be covered with separate RSIPs for each parameter, like
```yaml
  filter:
    labels:
      - "preview/from-scratch"
```
but with multiple parameters I think that would quickly get out of hand.

**Comment by stefanprodan** [comment]
@bo0tzz there is `.spec.defaultValues` where you would set any custom data you would need to for a specific PR label. The ResourceSet would be reusable across clusters, while the provider would come from an overlay:

On the dev cluster you would have an overlay that sets the label and defaults:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: flux-appx-prs
spec:
  filter:
    labels:
      - "deploy/dev-preview"
  defaultValues:
    db: "init"
    some: "dev-specific-setting"
```

On the staging cluster you would change the values:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: flux-appx-prs
spec:
  filter:
    labels:
      - "deploy/staging-preview"
  defaultValues:
    db: "snapshot"
    some: "staging-specific-setting"
```
