### ISSUE TITLE
Flux instance doesn't pick up `instance.sync.provider`

### ISSUE THREAD

**Issue by joryirving** [controlplaneio-fluxcd/flux-operator#180]
Trying to migrate flux 2.5.0 to using Github Apps for authentication, but the flux-instance isn't picking up `sync.provider`.
I can manually edit the `Girepository` and add the provider key and it works great.

```yaml
instance:
  distribution:
    version: 2.5.0
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    name: flux-system
    url: https://github.com/example/repo
    ref: refs/heads/main
    path: clusters/cluster1
    provider: github
    pullSecret: github-app
```

https://github.com/controlplaneio-fluxcd/flux-operator/blob/ff89550849b2f40d78d9e805912f50834010cb52/internal/controller/fluxinstance_controller.go#L345-L358
