### ISSUE TITLE
Issue moving to Github App authentication

### ISSUE THREAD

**Issue by chrede88** [controlplaneio-fluxcd/flux-operator#181]
I'm having some issues moving to Github App authentication. I used to use `ssh`, which I think might be the root cause here, but I'm not sure.

This is what I did:

1) Updated my `FluxInstance` to reference a new secret and created the secret (using kubectl apply) containing the Github App ID, install ID and private key.
2) Added the recommended kustomize patch (https://fluxcd.control-plane.io/operator/flux-sync/#sync-from-a-git-repository-using-github-app-auth) to the `FluxInstance`.
3) I left the `spec.url` at the old value (`ssh://git@github.com/org/repo.git`). Not intentional.

After reconcile, I noticed that the `GitRepository` had the follow status:
```
failed to configure authentication options: invalid 'ssh' auth option: 'identity' is required
```
This is what got me thinking about the url pointing to `ssh`.

4) using `kubectl edit`, I changed the `url` to `https://github.com/org/repo.git`. Now I get the following status:
```
failed to checkout and determine revision: could not parse private key: asn1: structure error: tags don't match (16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs8 @2
```

5) I've verified that the content of the new secret is correct:
```
k -n flux-system get secret github-auth -o yaml | yq '.data.githubAppID' | base64 -d
k -n flux-system get secret github-auth -o yaml | yq '.data.githubAppInstallationID' | base64 -d
k -n flux-system get secret github-auth -o yaml | yq '.data.githubAppPrivateKey' | base64 -d
```

Any idea what the issue might be? The status seems to be pointing at (what I assume) is the private key of the github app. But that checks out.

**Comment by stefanprodan** [comment]
Can you post here your FluxInstance as it is on the cluster also did you generated the `github-auth` secret with the flux CLI, does it have only those 3 keys?

**Comment by chrede88** [comment]
This is the `FluxInstance` that gave me the "private key" error:
```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    # renovate: datasource=github-releases depName=controlplaneio-fluxcd/distribution
    version: 2.5.0
    registry: ghcr.io/fluxcd
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    multitenant: false
    networkPolicy: true
    domain: cluster.local
  sync:
    kind: GitRepository
    url: https://github.com/chrede88/home-ops.git
    ref: refs/heads/main
    path: cluster/kubernetes/flux/main
    pullSecret: github-auth
  kustomize:
    patches:
      - patch: |
          - op: add
            path: /spec/decryption
            value:
              provider: sops
              secretRef:
                name: sops-age
        target:
          kind: Kustomization
      - patch: |
          - op: add
            path: /spec/provider
            value: github
        target:
          kind: GitRepository
```

Yes, the generated the `github-auth` secret using 
```
flux create secret githubapp github-auth \
  --app-id=<appID> \
  --app-installation-id=<installID> \
  --app-private-key=<path/to/file>
```

This is the secret as it's created on the cluster:
```yaml
apiVersion: v1
data:
  githubAppID: <base64encodedAppID>
  githubAppInstallationID: <base64encodedInstallID>
  githubAppPrivateKey: <base64EncodedPrivateKey>
kind: Secret
metadata:
  creationTimestamp: "2025-02-21T17:45:22Z"
  name: github-auth
  namespace: flux-system
  resourceVersion: "73530102"
  uid: 6bcebcbb-21ab-450f-859d-89461964b9ad
type: Opaque
```
