### ISSUE TITLE
`ResourceSet` generate ConfigMap/Secret with data copied from existing objects

### ISSUE THREAD

**Issue by stefanprodan** [controlplaneio-fluxcd/flux-operator#185]
When onboarding tenants and their apps on Kubernetes clusters, the cluster admins would define a [ResourceSet](https://github.com/controlplaneio-fluxcd/flux-operator/blob/main/docs/api/v1/resourceset.md) that generates the namespace, service account and RBAC needed to restrict the tenant's access.

There are cases when the newly created namespaces should contain ConfigMaps and Secrets which are common across the whole cluster. For example:
-  The [runtime-info](https://github.com/controlplaneio-fluxcd/d1-fleet/blob/main/clusters/staging/runtime-info.yaml) ConfigMap that holds the cluster info data used in Flux Kustomization [substituteFrom](https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution) which is created at bootstrap in the `flux-system` namespace.
-  The Kubernetes Image Pull Secret used for readonly access to container registries which are required to avoid rate limits when pulling public images from DockerHub/GHCR/etc.
- A ConfigMap that holds the common Helm values when using the [Generic Helm Charts Pattern](https://fluxcd.control-plane.io/guides/flux-generic-helm-chart/).

In order to facilitate the provisioning of these common configuration across namespaces, the ResourceSet API should allow users to tell the controller from where to copy ConfigMaps and Secrets data. The marker will be an annotation in the format `fluxcd.controlplane.io/copyFrom: "SOURCE-NAMESPACE/SOURCE-NAME"` placed inside the resources template.

Based on the ResourceSet reconciliation interval, the controller should verify if the origin ConfigMap/Secret has changed, and replicate the changes in the destination objects.

When the controller queries the Kubernetes API to fetch the source ConfigMap/Secret, it will impersonate the [Service Account assigned](https://github.com/controlplaneio-fluxcd/flux-operator/blob/main/docs/api/v1/resourceset.md#role-based-access-control) to the ResourceSet which is subject to RBAC and wouldn't allow copying data from a tenant's namespace to another.

## Example

Assuming the cluster admins want to provision a namespace per org team and configure the deployment of apps using Kubernetes manifests stored in DockerHub as Flux OCI artifacts.

At cluster bootstrap, a Kubernetes Image Pull Secret named `docker-auth` is created in the `flux-system` namespace using a DockerHub read-only token that allows pulling container images and OCI artifacts from the org repos. Also at bootstrap, a ConfigMap  named `runtime-info`  is created in the `flux-system` namespace., holding the cluster name, ingress domain and other runtime values.

### Flux Operator Config

The cluster admins will define a `ResourceSet` that generates a Kubernetes namespace per org team along with all the Kubernetes and Flux objects needed to deploy the team's apps in their dedicated namespace:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: tenants
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
  inputs:
    - tenant: "team1"
      artifact: "oci://docker.io/org/team1-apps"
    - tenant: "team2"
      artifact: "oci://docker.io/org/team2-apps"
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << inputs.tenant >>
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: runtime-info
        namespace: << inputs.tenant >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/runtime-info"
    - apiVersion: v1
      kind: Secret
      metadata:
        name: docker-auth
        namespace: << inputs.tenant >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/docker-auth"
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: flux
        namespace: << inputs.tenant >>
      imagePullSecrets:
        - name: docker-auth
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: flux
        namespace: << inputs.tenant >>
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
        - kind: ServiceAccount
          name: flux
          namespace: << inputs.tenant >>
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: OCIRepository
      metadata:
        name: apps
        namespace: << inputs.tenant >>
      spec:
        interval: 5m
        serviceAccountName: flux
        url: << inputs.artifact >>
        ref:
          tag: latest
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: apps
        namespace: << inputs.tenant >>
      spec:
        serviceAccountName: flux
        interval: 10m
        sourceRef:
          kind: OCIRepository
          name: apps
        path: "./"
        prune: true
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: runtime-info
```

Note that the ConfigMap and Secret do not have a `data` specified, instead these objects are annotate with the  `fluxcd.controlplane.io/copyFrom`. Every time Flux Operator reconciles the ResourceSet, the `data` fields will be synced 
from the `flux-system` namespace.
