### ISSUE TITLE
No feedback to end-user when ResourceSetInputProvider url is incorrect

### ISSUE THREAD

**Issue by erikgb** [controlplaneio-fluxcd/flux-operator#186]
I just started experimenting with this new feature in Flux Operator, so now I am doing the "dumb users" tests. 😉 

I configured a minimal `ResourceSetInputProvider` towards our GitLab:

````yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: flux-merge-requests
  namespace: egb-test
spec:
  type: GitLabMergeRequest
  url: <GitLab https Git URL>
````

This didn't work, as the resource wants the GitLab project URL, and not the https Git URL. 😅  But there is no feedback to the user about this, and the resource seems stale in a reconciling state:

````yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: flux-merge-requests
  namespace: egb-test
  generation: 1
status:
  conditions:
    - lastTransitionTime: '2025-02-22T15:14:23Z'
      message: Reconciliation in progress
      observedGeneration: 1
      reason: Progressing
      status: 'True'
      type: Reconciling
    - lastTransitionTime: '2025-02-22T15:14:23Z'
      message: Reconciliation in progress
      observedGeneration: 1
      reason: Progressing
      status: Unknown
      type: Ready
````

Luckily, I am a cluster admin in this cluster, so I have access to the Flux Operator logs. 😉 

````json
{"level":"error","ts":"2025-02-22T15:15:11.047Z","msg":"Reconciler error","controller":"resourcesetinputprovider","controllerGroup":"fluxcd.controlplane.io","controllerKind":"ResourceSetInputProvider","ResourceSetInputProvider":{"name":"flux-merge-requests","namespace":"egb-test"},"namespace":"egb-test","name":"flux-merge-requests","reconcileID":"cd36624a-42e6-4a9a-b57f-e41fd2a43e81","error":"failed to call provider: failed to list requests: could not list merge requests: 404 Not Found"}
````

Expected behavior is to give this feedback on the `ResourceSetInputProvider` status.
