### ISSUE TITLE
How to handle merge request that needs pipeline to be passed

### ISSUE THREAD

**Issue by hanstf** [controlplaneio-fluxcd/flux-operator#215]
We are currently using the `GitLabMergeRequest` `ResourceSetInputProvider` to detect for the new commit in the gitlab merge request, our `ResourceSet` has `HelmRelease` that accepts a `<<inputs.sha>>` image tag. This will deploy the `Deployment` with the new image since we separate our helm chart oci with application image.

The issue that we are facing now is, actually after a new commit push of that merge request, there is a CI that run some testing and building the new image which takes around 15 minutes, so at that time of `ResourceSet` reconciliation, the new image tag sha is not yet ready. Currently what we are doing is setting longer interval on the `HelmRelease` hoping that by the time the helm release is reconciled the image is ready. We also cant use the `ImagePolicy` comments on the `ResourceSet`.

Is there any way to conditionally use the previous exported inputs on a certain label so that we can set a label like `pipeline:pending` ? or any way we can gate this ?

Thanks!

**Comment by stefanprodan** [comment]
One option would be to trigger the `ResourceSetInputProvider` sync from CI at the end of the build pipeline, I would also set the RSIP interval to something like `1h`.

In the cluster create a Flux [generic receiver](https://fluxcd.io/flux/components/notification/receivers/#generic):

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: generic-receiver
  namespace: app-preview
spec:
  type: generic
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: app-merge-requests
```

Get the webhook URL from the `Receiver.status.webhookPath` and in the build job add a step with:

```sh
curl -X POST -d '{"do":"sync"}' http://webhook-receiver.flux-system/hook/XXXXXXX
```

**Comment by hanstf** [comment]
With this method, if there are 2 MRs, 1 pipeline is completed and another 1 is in progress, when the first pipeline is triggering the webhook, the issue will still exists right ?

Also means we need to open a hole for internet which is a bit hard

**Comment by matheuscscp** [comment]
Ideally there should be something RSIP controller can look at to decide if it's finally time to replace the inputs for the MR, but I'm not sure this approach with the labels is the best. What would be the workflow?

* I will push a new commit now. Add pending label first.
* Push new commit.
* Wait for pipeline to complete.
* Remove pending label and let RSIP reconcile.

Then repeat this every time I want to push a new commit? Wouldn't this be too manual?

**Comment by hanstf** [comment]
yup, so when a new commit is pushed, we will use the push options to add this label
`git push -o merge_request.label="pipeline:pending"` https://docs.gitlab.com/topics/git/commit/#:~:text=milestone=%223.0%22%20.,assign=%22user2%22%20.

once the pipeline completed, the pipeline job will remove that label.

Then in the RSIP, we can do something like this:
```
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: flux-appx-prs
  namespace: default
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
  type: GitHubPullRequest
  url: https://github.com/controlplaneio-fluxcd/flux-appx
  filter:
    labels:
      - "deploy/flux-preview"
  skip:
    labels:
      - "pipeline:pending"
```

if let say currently my last exportedInputs is:
```
[{
id: 1, branch: "a", sha: "123"
}, {
id: 2, branch: "b", sha: "234"
}]
```
In this case, when the "pipeline:pending" is exists in the branch "a" MR, the exportedInputs will still stay the same but when the "pipeline:pending" is removed, the sha of the branch "b" will be changed. Maybe we can use the id to do the compare?

I am not sure is this make sense or I can achieve it another way ?

**Comment by hanstf** [comment]
yup, that would be even better actually, we can use the head_pipeline to check for gitlab

but I am not sure how would you cater this for github, seems there is no quick way. Also how would you set the flag ? something like skipPipelineFailure in RSIP ?

**Comment by stefanprodan** [comment]
>Maybe we could look at something in the field .Pipeline?

I'm not for making this feature only for GitLab. Having some label that pauses the sync would work for any Git SaaS e.g. GitHub, AzureDevOps, Gitea, etc

**Comment by matheuscscp** [comment]
Sure, would work for all providers. But not a great experience though. The magic of automation gets completely shattered by this manual approach, I'd hate to use this workflow

**Comment by matheuscscp** [comment]
Using GitHub's GraphQL API it may be possible to list PRs including data from status checks with a single API call, which would be the equivalent of GitLab I believe

**Comment by matheuscscp** [comment]
I personally don't see an issue with taking advantage of provider capabilities in our code to offer a better UX. If some providers support some features but not others, it's up to users to choose what providers they use

**Comment by matheuscscp** [comment]
@hanstf What's exactly the impact of this issue for you? Is the new commit messing up the environment i.e. making it unusable while the pipeline has not finished?

**Comment by hanstf** [comment]
@matheuscscp it is not breaking our env, end user still able to navigate with the old pod. But since we are using HelmRelease, the helm upgrade will fails as the new pod will have ImagePullBackOff. 
Then it also seems that the "real" helm object is stuck at "failed" even when the pod has been running, this also causes when the MR is merged, the helm release controller seems left the "real" helm object hanging (not related to this topic). 

I am yet to try the upgrade.disableWait or upgrade.remediation.retries to infinity in HelmRelease, not sure will this helps.

**Comment by hanstf** [comment]
Nope, we are not. Maybe let me clarify, what I mean by the "real" helm object is the helm resource that managed by the HelmRelease created by the ResourceSet. So when you do helm list, the status is failed, then I need to manually uninstall it.

**Comment by stefanprodan** [comment]
> But since we are using HelmRelease, the helm upgrade will fails as the new pod will have ImagePullBackOff.

I guess your Kubernetes Deployment has the default `progressDeadlineSeconds` which is 10 minutes, that's the reason Helm fails the release as Kubernetes gives up on pulling the image after 10m while the build takes 15m. Increasing the deadline and setting `disableWait` would allow the deployment to rollout the new image at some point, but this will take a lot of time as the Kubernetes backoff is exponential.

**Comment by stefanprodan** [comment]
> The magic of automation gets completely shattered by this manual approach, I'd hate to use this workflow

I haven't suggested for this to be manual, this type of label that pauses the preview deployment is common practice in CI/CD, for example RedHat OperatorHub, Kubernetes e2e and lots more. The build pipeline that gets triggered for a new commit, can add the pause label when it starts and remove it only if the build & push was successful.

<img width="934" alt="Image" src="https://github.com/user-attachments/assets/f193c5ec-0741-4f87-8a84-f135fa7764ce" />

Having this pause feature in Flux Operator is useful beyond this use-case. You may want to pause the deployment while running e2e tests on the preview cluster which have nothing to do with the workflows inside the repo nor with the commit status.

**Comment by hanstf** [comment]
Ah I see, but is it expected behaviour when helm deemed the upgrade as failed and the HelmRelease cr is being removed, it does not remove the actual helm object and left all the resources underneath hanging and in the end I need to manually do the helm uninstall which makes it quite troublesome ?

I can try to work and PR on this label pausing around next week if you guys ok
Maybe is something I proposed before ?

`
skip:
    labels:
      - "pipeline:pending"
`

**Comment by stefanprodan** [comment]
> Is it expected behaviour when helm deemed the upgrade as failed and the HelmRelease cr is being removed, it does not remove the actual helm object and left all the resources underneath hanging and in the end I need to manually do the helm uninstall which makes it quite troublesome?

Please open an issue in helm-controller with an example we can reproduce. Let's keep this issue focused on Flux Operator.

**Comment by matheuscscp** [comment]
Yeah if we can combine with automation from somewhere else like GitHub Actions etc. or labels signaling readiness that looks good to me 👍

**Comment by dlidstrom** [comment]
There is a small delay (sometimes larger) associated with applying a label using GitHub actions. It is not certain that an agent will be immediately available to run the build after a commit. So this solution might cause the ResourceSet to trigger anyway on a new commit before the pausing label is available.

Another solution I can think of would be to require the existence of a git tag (perhaps one that matches a regexp). This works for any git provider as tags are a universal git feature (unlike labels). It also fits nicely into most ci setups as adding a tag is usually done at the end of a successful build. And it is also more transactional in nature than using labels which would rely on timing mechanisms.

**Comment by hanstf** [comment]
@dlidstrom the label also allows "!" prefix, so ideally we can set those label once the pipeline is succeed to resume the RSIP updates ?

For tag, do you mean we need to keep on adding tag even for MR branch ?

**Comment by stefanprodan** [comment]
Adding tags for each commit to a PR is not something I would consider, this will pollute the Git history and will trigger workflows that are meant for releasing.

**Comment by dlidstrom** [comment]
Just to let you know, I've implemented the skip labels solution with GitHub actions and it has been working great. Thanks! For reference, my actions look like this

```
- name: Remove label
  env:
    GH_TOKEN: ${{ github.token }}
    BRANCH: ${{ github.head_ref }}
  run: |
    gh pr edit "$BRANCH" --add-label deploy/needs-check

... rest of build ...

- name: Remove label
  env:
    GH_TOKEN: ${{ github.token }}
    BRANCH: ${{ github.head_ref }}
  run: |
    gh pr edit "$BRANCH" --remove-label deploy/needs-check
```
