### ISSUE TITLE
Kustomization resource kind errors in reports when kustomize-controller is not installed

### ISSUE THREAD

**Issue by crabique** [controlplaneio-fluxcd/flux-operator#218]
Hi!

When there is no kustomize-controller installed, every reporting interval Flux operator is posting a log entry like this one:
```json
{
  "level": "error",
  "ts": "2025-03-19T23:10:20.528Z",
  "msg": "report computed with errors",
  "controller": "fluxreport",
  "controllerGroup": "fluxcd.controlplane.io",
  "controllerKind": "FluxReport",
  "FluxReport": {
    "name": "flux",
    "namespace": "flux-system"
  },
  "namespace": "flux-system",
  "name": "flux",
  "reconcileID": "f339dd16-86bc-4415-b5f8-5bec72e0beaf",
  "error": "failed to compute sync status: source kind Kustomization not found"
}
```

The CRD indeed does not exist in this case:
```bash
$ kubectl get crd/kustomizations.kustomize.toolkit.fluxcd.io
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "kustomizations.kustomize.toolkit.fluxcd.io" not found
```
<br>

I see the check for the Kustomization kind is hardcoded here, but not 100% sure why this CRD in particular:
https://github.com/controlplaneio-fluxcd/flux-operator/blob/771cb784313a5f47f4d19e91c544281be2ffae65/internal/reporter/sync.go#L22-L29

Could you please clarify if this is even a supported use-case: to not need the Kustomize controller but still use the Flux operator?

**Comment by stefanprodan** [comment]
> Could you please clarify if this is even a supported use-case: to not need the Kustomize controller but still use the Flux operator?

This is not supported, kustomize-controller is the component that reconciles the desired state from Git or OCI Artifacts. There is no GitOps without it.

**Comment by crabique** [comment]
> Can you say more about your use-case?

I'm trying to achieve an isolated standalone image update automation flow that runs on a separate management cluster where no actual applications run: I have no need for Kustomization/Helm controllers as we don't use any Flux on that cluster otherwise, the CD for everything (including the Flux operator Helm chart and the `FluxInstance`) is handled by another GitOps system.

The idea is that it would only talk to the image registry (via polling and a webhook receiver) and update the state in git by updating the policy-marked image references in `values.yaml` files in the monorepo, then the global CD system would take over from there.

According to [this discussion in CNCF Slack](https://cloud-native.slack.com/archives/CLAJ40HV3/p1741379057394629) it should be a supported use-case (at least on paper).

In the `FluxInstance` I have the following spec with only the controllers that provide the APIs I intend to use:
```YAML
spec:
  components:
    - source-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
```

This deploys just fine and seems to work as expected, besides those reporter errors.

> This is not supported, kustomize-controller is the component that reconciles the desired state from Git or OCI Artifacts.

So do I understand correctly that the kustomize-controller is used for internal needs of the Flux operator itself: to handle the `fluxcd.controlplane.io/reconcile` annotation-controlled distribution reconciliation loop? If that's the case, would it make sense to make the kustomize-controller a hard dependency that would always be deployed even if it's omitted in the components list? 

Alternatively, would you recommend using the community chart as a more flexible alternative in this case? I do not really care very much about the distribution reconciliation loop, the updates would be handled explicitly by Renovate integration on the charts level.

**Comment by stefanprodan** [comment]
> So do I understand correctly that the kustomize-controller is used for internal needs of the Flux operator itself

No, it's only used when you have `.spec.sync` in the FluxInstance. 

> I'm trying to achieve an isolated standalone image update automation flow that runs on a separate management cluster where no actual applications run

So don't you need a to sync the ImagePolicies and repo definitions on this cluster? I would expect for such a cluster to set the Flux instance `.spec.sync.path` to where the image automation manifests are.

**Comment by stefanprodan** [comment]
Ok you can disable the reporting as you don't need it: `kubectl -n flux-system annotate --overwrite fluxreport/flux 
 fluxcd.controlplane.io/reconcile=disabled`.

When you apply the image manifests, you could also include a FluxReport manifest with that annotation, like this:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxReport
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "disabled"
spec:
  distribution:
    entitlement: "unknown"
    status: "unknown"
```

**Comment by crabique** [comment]
> Ok you can disable the reporting as you don't need it

Thanks! Would this still produce the `flux_resource_info` metrics?

**Comment by stefanprodan** [comment]
> Would this still produce the flux_resource_info metrics?

Nop

**Comment by stefanprodan** [comment]
Can you please try to scale to zero kustomize-controller and see of it works. This would be the best solution without changing the code that assumes the CRD is present.

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
spec:
  kustomize:
    patches:
      - patch: |
          - op: replace
            path: /spec/replicas
            value: 0
        target:
          kind: Deployment
          name: kustomize-controller
```
