### ISSUE TITLE
ResourceSet should support input defaults

### ISSUE THREAD

**Issue by erikgb** [controlplaneio-fluxcd/flux-operator#225]
We are trying to `ResourceSet` to mass-produce instances of tenant features in our cluster. The tenants are supposed to provide us with their input, which works nicely. But I think `ResourceSet` should provide "input defaults". Here is how our RS currently looks like:

````yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: s3-tenants
  namespace: flux-tenants
spec:
  # To onboard a tenant in s3, add its namespace to the inputs:
  # - namespace: <tenant-namespace>
  inputs:
    - namespace: acme
      storageBytes: 10Gi
    - namespace: utvt
  resources:
    - apiVersion: s3.statnett.no/v1alpha1
      kind: Tenant
      metadata:
        name: << get inputs "name" | default inputs.namespace >>
        namespace: << inputs.namespace >>
      spec:
        description: << get inputs "description" | default inputs.namespace >>
        limits:
          storage:
            bytes: << get inputs "storageBytes" | default "100Gi" >>
````

As you can see, we want static input defaults and defaults from other inputs. A default from another input is probably too complex to support in Flux Operator, but static input defaults would make this look a lot better - at least for our tenants. Then they would see the available inputs, including the default value. Omitting irrelevant details, this could become as simple as:

````yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: s3-tenants
spec:
  inputDefaults:
    storageBytes: 100Gi
  inputs:
    - namespace: acme
      storageBytes: 10Gi
    - namespace: utvt
  resources:
    - apiVersion: s3.statnett.no/v1alpha1
      kind: Tenant
      spec:
        limits:
          storage:
            bytes: << inputs.storageBytes >>
````

WDYT?

Slightly relevant: https://github.com/controlplaneio-fluxcd/distribution/pull/179
