### ISSUE TITLE
Support inputs templating in ResourceSet common metadata

### ISSUE THREAD

**Issue by erikgb** [controlplaneio-fluxcd/flux-operator#226]
We have a use case for applying a common label to all resources in a `rset' but the label is a function of the input. Is there a reason we should not support something like this:

````
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
spec:
  inputs:
    - tenant: stas
    - tenant: strm
  commonMetadata:
    labels:
      toolkit.fluxcd.io/tenant: << inputs.tenant >>
````

Relates to https://github.com/controlplaneio-fluxcd/flux-operator/issues/183.

**Comment by bgdnlp** [comment]
I was looking for the same thing and found this issue. Since the data in `commonMetadata` is conceptually part of `resources` and `resourcesTemplate` it makes sense to be able to template it.

Another example would be having a template RSET for a type of application (like frontend+backend+DB):
```
commonMetadata:
  labels:
    app.kubernetes.io/part-of: << inputs.applicationName >>
```

**Comment by stefanprodan** [comment]
The `commonMetadata` is common to all generated resources, if you template it, then this would be a major breaking change in the API, also the name would not make sense anymore, as it's not common to all.

**Comment by bgdnlp** [comment]
I'm missing something. Aren't these two basically the same? If it were possible to use inputs in `commonMetadata` I mean.
```
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: << inputs.projectName >>
  resources:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: << inputs.appName >>
        labels:
          app.kubernetes.io/name: << inputs.appName >>
      spec:
        (...)
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: << inputs.appName >>
        labels:
          app.kubernetes.io/name: << inputs.dbName >>
      spec:
        (...)
```
and
```
spec:
  resources:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: << inputs.appName >>
        labels:
          app.kubernetes.io/name: << inputs.appName >>
          app.kubernetes.io/part-of: << inputs.projectName >>
      spec:
        (...)
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: << inputs.appName >>
        labels:
          app.kubernetes.io/name: << inputs.dbName >>
          app.kubernetes.io/part-of: << inputs.projectName >>
      spec:
        (...)
```

We can template (as in "replace with a variable value") the `part-of` label when it's under `spec.resources`, why not when it's under `spec.commonMetadata`?
