### ISSUE TITLE
Patching resources in a ResourceSet?

### ISSUE THREAD

**Issue by mattfield** [controlplaneio-fluxcd/flux-operator#240]
I might be thinking about this the wrong way, but what's the advised approach to patching resources in a ResourceSet? For example, patching values in a HelmRelease. I have a working solution using Kustomize but it's quite brittle due to needing to take this kind of approach when targeting list items:

```yaml
- op: test
  path: /spec/resources/1/kind
  value: HelmRelease
- op: add
  path: /spec/resources/1/spec/values
  value:
    server:
      ...
```

I guess the ResourceSet(s) could be wrapped/deployed in a Kustomization, and patches introduced that way, but I think I'd still be patching the rset rather than the resources contained in the rset.

Or, is the RSIP the main way of handling this, by having inputs defined elsewhere and then included? Such as default HelmRelease values in an rset with extra values pulled from a RSIP, using the same example.

(as an aside, when both `.spec.inputs` and `.spec.inputsFrom` are provided, the docs say "union" which to me implies a merge, but the rset CRD field/rset controller reads like they're just concatenated).
