### ISSUE TITLE
Does FluxInstance/spec/sync/pullSecret support sops decryption?

### ISSUE THREAD

**Issue by kodal** [controlplaneio-fluxcd/flux-operator#247]

**Comment by matheuscscp** [comment]
Short answer is no. Can you please be more specific?

**Comment by kodal** [comment]
For declarative bootstrap with secretGenerator (apply GitHub token with kustomize)

**Comment by stefanprodan** [comment]
You can enable decryption in the Flux Kustomization generated by the FluxInstance sync. Docs here: https://fluxcd.control-plane.io/operator/flux-kustomize/#cluster-sync-sops-decryption

**Comment by matheuscscp** [comment]
> For declarative bootstrap with secretGenerator (apply GitHub token with kustomize)

If I understand what you're asking for correctly, on bootstrap you'd need to SOPS-decrypt the secret yourself, and then after bootstrap the sync Kustomization could take over with the docs pointed by Stefan above

**Comment by kodal** [comment]
> You can enable decryption in the Flux Kustomization generated by the FluxInstance sync. Docs here: https://fluxcd.control-plane.io/operator/flux-kustomize/#cluster-sync-sops-decryption

I seek a sops-decryption for FluxInstance/sync/pullSecret (for GitRepository)

**Comment by kodal** [comment]
> > For declarative bootstrap with secretGenerator (apply GitHub token with kustomize)
> 
> If I understand what you're asking for correctly, on bootstrap you'd need to SOPS-decrypt the secret yourself, and then after bootstrap the sync Kustomization could take over with the docs pointed by Stefan above

I have applied sops-age decryption with

```
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: sops-age
    namespace: flux-system
    files:
      - .agekey
``` 

flux-instance.yaml

```
---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
  sync:
    kind: GitRepository
    url: "https://github.com/kodal/home-capi"
    ref: "refs/heads/main"
    path: "clusters/staging"
    pullSecret: "flux-system"
  kustomize:
    patches:
      - patch: |
          - op: add
            path: /spec/postBuild
            value:
              substitute:
                PIVOT: "${PIVOT:=false}"
              substituteFrom:
                - kind: ConfigMap
                  name: runtime-info
                  optional: true
        target:
          kind: Kustomization
      - patch: |
          - op: add
            path: /spec/decryption
            value:
              provider: sops
              secretRef:
                name: sops-age
        target:
          kind: Kustomization

```

But FluxIntance/sync/pullSecret not decrypted with sops-age.


```
resources:
  - flux-instance.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: flux-system
    namespace: flux-system
    literals:
      - username=kodal
    files:
      - password=github.token.enc
```
