### ISSUE TITLE
ResourceSet templating: function "bool" not defined

### ISSUE THREAD

**Issue by darylgraham** [controlplaneio-fluxcd/flux-operator#263]
**flux-operator version: 0.20.0**

I have a ResourceSet that builds a set of Kustomization files for some apps and I was updating it using the "assign a default value when an input field is not specified" example from the [ResourceSet templating](https://fluxcd.control-plane.io/operator/resourceset/#templating-functions) documentation.

The same doc mentions to convert booleans in templates:
>When templating booleans, use the bool function to convert the string to a boolean e.g. << inputs.enabled | bool >>.

When trying to use `<< get inputs "wait" | default "true" | bool >>` the cli `build` command throws an error: `function "bool" not defined`. 

Removing the `| bool` resolves the error.

Example file:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: core-apps
spec:
  inputs:
    - service: "app1"
      wait: "false"
    - service: "app2"
      wait: "false"
    - service: "app3"
    - service: "app4"
  resourcesTemplate: |
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: core-<< inputs.service >>
      namespace: flux-system
    spec:
      path: "./"
      interval: 10m
      wait: << get inputs "wait" | default "true" | bool >>
      sourceRef:
        kind: OCIRepository
        name: core-<< inputs.service >>

```

```bash
$ flux-operator build rset -f file.yaml 
✗ failed to build resources: failed to parse multi-doc YAML template: template: resourceset:10: function "bool" not defined
```
