### ISSUE TITLE
Kustomize secretGenerator vs ResourceSet

### ISSUE THREAD

**Issue by TamasSzigeti** [controlplaneio-fluxcd/flux-operator#271]
Hello, absolutely grateful for this project, ResourceSet is a great tool.

When I add e.g. a Deployment to a ResourceSet, and attempt to inject secrets via envFrom, the regular kustomize suffixing (to trigger updates) doesn't work, it tries to find the secret without the suffix.

**Comment by stefanprodan** [comment]
You need to teach Kustomize how to find the Secrets/ConfigMaps inside the ResourceSet. Can you post here the ResourceSet and your kustomization.yaml

**Comment by stefanprodan** [comment]
Ok so you need a kustomizeconfig.yaml with something like:

```yaml
nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/resources/spec/template/spec/containers/envFrom/secretRef/name
    kind: ResourceSet
```
