### ISSUE TITLE
0.21.0 is missing support for source.toolkit.fluxcd.io/v1 required for some sync sources in FluxCD 2.6.0

### ISSUE THREAD

**Issue by judgeaxl** [controlplaneio-fluxcd/flux-operator#279]
0.21.0 still generates resource version `source.toolkit.fluxcd.io/v1beta2` for sync sources, which means especially the Bucket source don't conform and will fail the dry-run for a `FluxInstance` targeting a 2.6.0 cluster. Specifically the `spec.url` field is reported as unknown and applying the source fails.

Repro steps:

- Deploy flux-operator 0.21.0 to a cluster
- Create a FluxInstance with a sync spec for a Bucket:

```
spec:
  sync:
    kind: Bucket
    url: "minio.my-org.com"
    ref: "my-bucket-fleet"
    path: "clusters/my-cluster"
    pullSecret: "bucket-auth"
```

- Follow the logs and see that it fails to generate the sync source resource. Other resources are still applied as expected.
