### ISSUE TITLE
Enhancement: Automatic PVC generation per shard when using sharding with persistent storage

### ISSUE THREAD

**Issue by vterdunov** [controlplaneio-fluxcd/flux-operator#285]
When using FluxInstance `spec.sharding` combined with `spec.storage`, the Flux Operator currently only creates a single PVC and configures persistent storage for the first shard (shard0). Additional shards (shard1, shard2, etc.) are left with emptyDir storage, which creates an inconsistent storage configuration across shards.

```
spec:
  sharding:
    key: "sharding.fluxcd.io/key"
    shards:
      - "shard1"
      - "shard2"
  storage:
    class: "gp3"
    size: "10Gi"
```

Proposed Enhancement
Enhance the Flux Operator to automatically generate individual PVCs for each shard when both spec.sharding and spec.storage are configured. Each source-controller shard should be configured with its own persistent storage instead of only the first shard.
