### ISSUE TITLE
Ability to select latest tags like Flux `ImagePolicy` in `ResourceSetInputProvider`

### ISSUE THREAD

**Issue by matheuscscp** [controlplaneio-fluxcd/flux-operator#321]
Flux `ImagePolicy` has proven very useful with the ability to select a latest tag from a set using semver, alphabetical and numerical sorting. Now that `ResourceSetInputProvider` has lots of providers for fetching both Git and OCI tags, it would be really good if it could do the same as `ImagePolicy`. Furthermore, following the principle of improved writing capability of `ResourceSets`, we should also strive to build something that can decrease the amount of boilerplate required by several `ImagePolicy` objects.

### Proposal

We propose the following new fields to be added:

- `.spec.filter.extractValue`. A template that can be expanded using the `.spec.filter.includeTag` regex matching result to extract a string from a tag for usage with sorting, order comparison and string matching (hence why the name of the field is so broad, it's not just for ordering). If not specified, the tag itself is used for these purposes. If `spec.filter.semver` is specified, the extracted value is used for matching the semver range.
- `.spec.filter.orderBy`. An order to sort tags with. Can be one of `SemVer`, `Alphabetical`, `ReverseAlphabetical`, `Numerical` or `ReverseNumerical`. When `.spec.filter.semver` is specified, this field will immediately assume the value `SemVer` and no other values can be assigned. When `.spec.filter.semver` is not specified, the default value for this field will be `ReverseAlphabetical` (this default behavior is introduced [here](https://github.com/controlplaneio-fluxcd/flux-operator/pull/320)).
- `.spec.filter.extractGroup`. A template that can be expanded using the `.spec.filter.includeTag` regex matching result to extract a string from a tag for defining its group. The extracted string will serve as a group key. Tags yielding the same group key will be placed in the same group. If not specified, only a single group with all the tags is defined. When the scan results in multiple groups, `.spec.filter.limit` will apply to each group individually. For example, if the limit is 1 and the scan results in 10 groups of tags, 10 tags will be exported in the status. If the limit is 3 and the scan results in 10 groups, up to 30 tags will be exported. Additionaly, when the scan results in multiple groups, the tags will be exported in the alphabetical order of the group keys, then inside each group with the order defined by `.spec.filter.orderBy`.

All this logic can also be applied for branches, but we leave this out-of-scope for now. None of the new fields have `tag` or `branch` on them, so they can be supported for branches in the future (alongside `.spec.filter.includeBranch`).

### Examples

Export a single latest tag according to the default order (`ReverseAlphabetical`):

```yaml
spec:
  filter:
    limit: 1
```

Export a single latest tag according to SemVer:

```yaml
spec:
  filter:
    orderBy: SemVer
    limit: 1
```

Export a single latest tag according to a SemVer range:

```yaml
spec:
  filter:
    semver: ">=1.0.0 <2.0.0" # this forces the value SemVer for .orderBy
    limit: 1
```

Export a single latest tag according to SemVer extracting the version with a regex:

```yaml
spec:
  filter:
    includeTag: "^([a-z]+)-([a-z]+)-(v.+)$"
    extractValue: $3
    orderBy: SemVer
    limit: 1
```

Export a single latest tag according to a SemVer range extracting the version with a regex:

```yaml
spec:
  filter:
    includeTag: "^([a-z]+)-([a-z]+)-(v.+)$"
    extractValue: $3
    semver: ">=1.0.0 <2.0.0" # this forces the value SemVer for .orderBy
    limit: 1
```

Export a single latest tag according to a timestamp extracting it with a regex:

```yaml
spec:
  filter:
    includeTag: "^([a-z]+)-([a-z]+)-([0-9]+)$"
    extractValue: $3
    orderBy: ReverseNumerical
    limit: 1
```

Export one latest tag per group according to SemVer, extracting the version and group key with a regex:

```yaml
spec:
  filter:
    includeTag: "^([a-z]+)-([a-z]+)-(v.+)$"
    extractGroup: $1-$2
    extractValue: $3
    orderBy: SemVer
    limit: 1
```

Export one latest tag per group according to a timestamp, extracting the timestamp and group key with a regex:

```yaml
spec:
  filter:
    includeTag: "^([a-z]+)-([a-z]+)-([0-9]+)$"
    extractGroup: $1-$2
    extractValue: $3
    orderBy: ReverseNumerical
    limit: 1
```

Export at most 3 latest tags per group according to SemVer, extracting the version and group key with a regex:

```yaml
spec:
  filter:
    includeTag: "^([a-z]+)-([a-z]+)-(v.+)$"
    extractGroup: $1-$2
    extractValue: $3
    orderBy: SemVer
    limit: 3
```
