### ISSUE TITLE
Use input templates in CEL health checks

### ISSUE THREAD

**Issue by piontec** [controlplaneio-fluxcd/flux-operator#323]
I'm trying to come up with a solution where a `rset` is only deployed if another Deployment already is upgraded to the newest version. In terms of `podinfo`, I want my `rset` to automatically render with a new version when the Deployment `podinfo` in the `default` namespace is already running that version.

rsip:
```yaml
---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: podinfo-tags-update
  namespace: default
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
  type: GitHubTag
  url: https://github.com/stefanprodan/podinfo
  filter:
    limit: 1
    semver: ">=6.9.0"
```

rset:
```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: podinfo-update
  namespace: default
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
spec:
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: podinfo-tags-update
  wait: true
  dependsOn:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: default
      ready: true
      readyExpr: |
        metadata.generation == status.observedGeneration &&
        metadata.labels['app.kubernetes.io/version'] == << inputs.tag | quote >>
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: podinfo-update
        namespace: default
      spec:
        interval: 10m
        url: oci://ghcr.io/stefanprodan/charts/podinfo
        ref:
          semver: << inputs.tag | quote >>
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: podinfo-update
        namespace: default
      spec:
        interval: 1h
        releaseName: podinfo
        chartRef:
          kind: OCIRepository
          name: podinfo-update
```

But it seems you can't use input variables in the CEL expression, as the status of the `rset` is
```
Message:               Reconciliation failed terminally due to configuration error: failed to parse expression for dependenc
y apps/v1/Deployment/default/podinfo: failed to parse the CEL expression 'metadata.generation == status.observedGeneration &&   
metadata.labels['app.kubernetes.io/version'] == << inputs.tag | quote >>                                                        
': ERROR: <input>:2:49: Syntax error: mismatched input '<' expecting {'[', '{', '(', '.', '-', '!', 'true', 'false', 'null', NUM
_FLOAT, NUM_INT, NUM_UINT, STRING, BYTES, IDENTIFIER}                                                                           
 | metadata.labels['app.kubernetes.io/version'] == << inputs.tag | quote >>                                                     
 | ................................................^                                                                            
ERROR: <input>:2:50: Syntax error: extraneous input '<' expecting {'[', '{', '(', '.', '-', '!', 'true', 'false', 'null', NUM_FL
OAT, NUM_INT, NUM_UINT, STRING, BYTES, IDENTIFIER}                                                                              
 | metadata.labels['app.kubernetes.io/version'] == << inputs.tag | quote >>                                                     
 | .................................................^                                                                           
ERROR: <input>:2:63: Syntax error: token recognition error at: '| '                                                             
 | metadata.labels['app.kubernetes.io/version'] == << inputs.tag | quote >>                                                     
 | ..............................................................^                                                              
ERROR: <input>:2:65: Syntax error: mismatched input 'quote' expecting <EOF>                                                     
 | metadata.labels['app.kubernetes.io/version'] == << inputs.tag | quote >>                                                     
 | ................................................................^
```

Is this a bug or a known limitation that I missed?

**Comment by matheuscscp** [comment]
It's not a bug. The template-able fields are only .spec.resources and .spec.resourcesTemplate

**Comment by matheuscscp** [comment]
One of the implications of fetching the inputs before checking the dependencies is that you no longer can, for example, depend on the input provider objects themselves to make sure they're ready to provide valid inputs... (Just thinking about the feasibility of this feature request...)

**Comment by piontec** [comment]
Hmm, why not? Input providers are about "me" (a `rset`), while health checks are about "others" (objects that I want to evaluate). So, to my mind, the control flow could go like this:
1. Are my `rsip`s ready? If not, I can't reconcile my state (and if that's for `spec.resources` only, it's still the same: I can't apply the `rset` output, as I don't know what is looks like withtout `rsip`s ready)
2. `rsip`s ready, let's render CEL expressions and apply them. If the CEL expression evaluates to `false` - health checks fail.
3. If health checks are OK, we can proceed and template `resources(Template)`

On a more general note: what I'm trying to achieve here is "update `rset` called `dep` to a newer version only if another object (can be limited to another `rset`, by evaluating its `inputs`) is already in version (at least) `v1`".
As an example: I want to pause upgrades and deployment of a `rset` until another Deployment/RSet is in at least version `1.2.3`.

**Comment by matheuscscp** [comment]
Fair 🤔 This use case sounds valid to me

**Comment by stefanprodan** [comment]
> I want to pause upgrades and deployment of a rset until another Deployment/RSet is in at least version 1.2.3.

This will be possible in Flux 2.7 by adding a CEL expression to the generated Flux object from the ResourceSet:
- https://github.com/fluxcd/kustomize-controller/pull/1491
- https://github.com/fluxcd/helm-controller/pull/1271

## Example

We define two ResourceSets:

- app-backend-bundle
- app-frontend-bundle

The app-backend-bundle labels the HelmRelease with the `app/version` (this is our upgrade mutex):

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: app-backend-bundle
  namespace: default
spec:
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: app-tags-update
  wait: true
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: app-backend
        namespace: default
      spec:
        interval: 10m
        url: oci://ghcr.io/stefanprodan/charts/podinfo
        ref:
          semver: << inputs.tag | quote >>
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: app-backend
        namespace: default
        labels:
          # lockstep upgrade with frontend version
          app/version: << inputs.tag | quote >>
      spec:
        interval: 1h
        releaseName: app-backend
        chartRef:
          kind: OCIRepository
          name: app-backend
```

The app-frontend-bundle generates a HelmRelease where the upgrade is conditioned by the shared `app/version`:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: app-frontend-bundle
  namespace: default
spec:
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: app-tags-update
  dependsOn:
    - apiVersion: apps/v1
      kind: ResourceSet
      name: app-backend-bundle
      namespace: default
      ready: true
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: app-frontend
        namespace: default
      spec:
        interval: 10m
        url: oci://ghcr.io/stefanprodan/charts/podinfo
        ref:
          semver: << inputs.tag | quote >>
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: app-frontend
        namespace: default
        labels:
          app/version: << inputs.tag | quote >>
      spec:
        dependsOn:
          - name: app-backend
          # lockstep upgrade with backend version
            readyExpr: >
              dep.metadata.labels['app/version'] == self.metadata.labels['app/version'] &&
              dep.status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True') &&
              dep.metadata.generation == dep.status.observedGeneration
        interval: 1h
        releaseName: app-frontend
        chartRef:
          kind: OCIRepository
          name: app-frontend
```
