### ISSUE TITLE
`ResourceSet` staged server-side apply

### ISSUE THREAD

**Issue by matheuscscp** [controlplaneio-fluxcd/flux-operator#329]
Kubernetes server-side apply dry-run is not [designed](https://kubernetes.slack.com/archives/C0EN96KUY/p1749806105108539) to be transactional, so it fails very often for cross-resource applies, i.e. for resources that check the existence of other resources being applied as part of the same operation. This fails because dry-run does not persist the operation and does not keep track of what's being applied and referenced in the same apply. This is often a UX issue in Kubernetes: https://github.com/fluxcd/pkg/issues/956

To improve this for users, I propose a new field in the `ResourceSet` API, `.spec.stages`:

```yaml
spec:
  stages:
  - name: roles
    resources:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      rules: ...
    resourcesTemplate: |
      ...
  - name: role-bindings
    resources:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      roleRef: ...
      subjects: ...
```

The stages are applied in the defined order. Before applying each stage, the operator should wait (like `ApplyAllStaged()` and kustomize-controller do) and commit the change set of the previous stage to the `.status.inventory` field. These phased commits to the inventory allow the operator to keep track and garbage-collect everything when a failure happens at any given stage, being it due to a failed dry-run check or an apply timeout.

By introducing also a field `.status.inventory.stages` like in the example below, the operator can resume failed applies from the stage that failed and can also garbage-collect the resources in the reverse order of apply, ensuring consistency across the lifecycle:

```yaml
status:
  inventory:
    stages:
    - name: roles
      entries: ...
    - name: role-bindings
      entries: ...
```

We can also introduce the field `.status.failedStage` with the `name` of the stage that failed when that happens. Stage names must be unique.

I appreciate this is a complex solution and may need more real use cases to justify.

One use case I can think of is reducing boilerplate for tenant provisioning. For example, in the past we concluded that, for users to restrict RBAC for Flux object-level workload identity, the tenant provisioning RSET would need to be broken down into at least the following stages (or something close):

- Roles and ServiceAccounts
- RoleBindings
- Everything else

I think this can be a great UX improvement, and it's aligned with the design goal of making the Flux Operator APIs reduce the YAML boilerplate required for using Flux. By allowing multiple stages to be defined in the same RSET we not only spare multiple RSETs, but also ensure the consistency when fetching inputs from dynamic sources (which is not the case in tenant provisioning, but staged apply is also needed in other scenarios).
