### ISSUE TITLE
Multitenant Service Account

### ISSUE THREAD

**Issue by blezoray** [controlplaneio-fluxcd/flux-operator#44]
Today, in version 0.5.0, we can change the multitenant Service Account using kustomize patch, like this:
```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
spec:
...
  cluster:

    type: openshift
    multitenant: true
    networkPolicy: true
    domain: "cluster.local"
...
  kustomize:
    patches:
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --default-service-account=flux
        target:
          kind: Deployment
          name: "(kustomize-controller|helm-controller)"
```

As the result, the kustomize|helm controllers have these args (`flux` SA overwrite `default` SA):
```yaml
  spec:
    containers:
      - args:
          - --events-addr=http://notification-controller.mpms-flux-operator.svc.cluster.local./
          - --watch-all-namespaces=true
          - --log-level=info
          - --log-encoding=json
          - --enable-leader-election
          - --no-cross-namespace-refs=true
          - --no-remote-bases=true
          - --default-service-account=default
          - --concurrent=10
          - --requeue-dependency=5s
          - --default-service-account=flux
```

Is it possible to add a new parameter, like `spec.cluster.multitenantServiceAccountName` in order to specify the name of this SA and to avoid any confusion ?

Rgds, Bruno.
