### ISSUE TITLE
Pull Flux manifests from registry with private PKI certificate

### ISSUE THREAD

**Issue by erikgb** [controlplaneio-fluxcd/flux-operator#66]
Our cluster does not have a direct connection to the Internet, and must pull all images through a registry proxy. This registry is configured with a certificate chain rooted in our private self-signed CA. How can I make Flux Operator trust this root?

This error is logged from Flux Operator:

````json
{"level":"error","ts":"2024-07-04T12:03:33.625Z","msg":"Reconciler error","controller":"fluxinstance","controllerGroup":"fluxcd.controlplane.io","controllerKind":"FluxInstance","FluxInstance":{"name":"flux","namespace":"flux-system"},"namespace":"flux-system","name":"flux","reconcileID":"90115059-3e19-4cc3-ad0a-8af12fe0f077","error":"pulling artifact oci://<REDACTED>/ghcr-docker-remote/controlplaneio-fluxcd/flux-operator-manifests failed: Get \"https://<REDACTED>/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
````

Flux Operator version: 0.6.0
Flux Operator installation method: OLM (operatorhub.io Subscription)

FluxInstance resource (irrelevant details omitted):

````yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    artifact: 'oci://<REDACTED>/ghcr-docker-remote/controlplaneio-fluxcd/flux-operator-manifests'
    registry: ghcr.io/fluxcd
    version: 2.3.x
````

Note: Our CRIO config will ensure the `registry` (for Flux images), is rewritten when images are pulled by our cluster.

**Comment by stefanprodan** [comment]
If you're using OperatorHub you don't need the artiract, OLM knows how to automatically update the Flux Operator, and the operator has the manifests embedded for air-gapped use. This would only be a problem if you would be an Enterprise customer, the artifact contains the CVE patches that we ship for Flux.

**Comment by erikgb** [comment]
Ahhh, so I can just remove `distribution` completely, or? I would like to have some control over the Flux version, tho.

**Comment by stefanprodan** [comment]
Anyway let's keep this issue opened as paying customers will actually have a problem with this.

**Comment by erikgb** [comment]
> You would remove only the `.spec.distribution.artifact` field. If you look at the example FluxInstance on OperatorHub, you'll see that this field is not there.

I confirm that the suggested fix (simplification) solved our issue in the air-gapped cluster! 🥳 Thanks Stefan! ❤️

**Comment by lllamnyp** [comment]
> If you're using OperatorHub you don't need the artiract, OLM knows how to automatically update the Flux Operator, and the operator has the manifests embedded for air-gapped use. This would only be a problem if you would be an Enterprise customer, the artifact contains the CVE patches that ControlPlane ships for Flux.

@stefanprodan we're installing the operator with the helm chart, but I guess it has the manifests embedded either way, right?

**Comment by a1994sc** [comment]
I think that this issue is still relevant, as if you wanted to use a custom fluxcd distribution. I feel like if you pull in similar logic from the [`fluxcd/source-controller`](https://github.com/fluxcd/source-controller/blob/39b711b111fa906c3db0a424e252a5d12e48646d/api/v1/ocirepository_types.go#L99-L112), to have an optional field `.spec.distribution.certSecretRef` to reference a kubernetes secret with a CA included for the private registry.

```go
	// CertSecretRef can be given the name of a Secret containing
	// either or both of
	//
	// - a PEM-encoded client certificate (`tls.crt`) and private
	// key (`tls.key`);
	// - a PEM-encoded CA certificate (`ca.crt`)
	//
	// and whichever are supplied, will be used for connecting to the
	// STS endpoint. The client cert and key are useful if you are
	// authenticating with a certificate; the CA cert is useful if
	// you are using a self-signed server certificate. The Secret must
	// be of type `Opaque` or `kubernetes.io/tls`.
	//
	// This field is only supported for the `ldap` provider.
	// +optional
	CertSecretRef *meta.LocalObjectReference `json:"certSecretRef,omitempty"`
``` 

the alternative seems to override the SSL Cert store with a something like the following, (if you are doing an install from the operator helm chart):

```yaml
extraEnvs:
  - name: SSL_CERT_FILE
    value: /etc/custom/ca.crt

extraVolumes:
  - name: custom-registry
    secret:
      secretName: custom-registry-tls

extraVolumeMounts:
  - name: custom-registry
    mountPath: /etc/custom/ca.crt
    readOnly: true
    subPath: ca.crt

```
