### ISSUE TITLE
Add flux operator in the Redhat Community catalog

### ISSUE THREAD

**Issue by blezoray** [controlplaneio-fluxcd/flux-operator#72]
Hello,

Today, flux-operator is in the OperatorHub community repo: https://github.com/k8s-operatorhub/community-operators/tree/main/operators/flux-operator

But not in the official Redhat community repo, which is used to build the Community catalog automatically deployed on Openshift: https://github.com/redhat-openshift-ecosystem/community-operators-prod

Could you add it to this repo ?

Rgds.

**Comment by stefanprodan** [comment]
We plan to have the Flux Enterprise distribution in the official RedHat marketplace, OpenShift customers would have to purchase a subscription to get the operator and the hardened Flux images. But I'm not sure if the community-operators and the marketplace are the same thing.

**Comment by blezoray** [comment]
By default, there are 4 catalogs:
![image](https://github.com/user-attachments/assets/b20221c6-3324-49c5-8b1f-2ce4cef2cbc6)
I think the "commercial" one is Marketplace.

**Comment by stefanprodan** [comment]
@blezoray can you confirm please that flux-operator shows up in Community catalog, a screenshot would be great, thanks!

**Comment by blezoray** [comment]
Hi, I confirm we can see the operator in the Community catalog.
![image](https://github.com/user-attachments/assets/95645044-c723-48db-bf84-1bd7bf54e66d)

Thanks a lot

**Comment by blezoray** [comment]
And the deployment in version 0.8.0 works perfectly.
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: flux-operator
  namespace: mpms-flux-operator
spec:
  channel: stable
  installPlanApproval: Manual
  name: flux-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: flux-operator.v0.8.0
  config:
    resources:
      requests:
        cpu: 50m
        memory: 230Mi
      limits:
        cpu: 200m
        memory: 500Mi
```
