### ISSUE TITLE
FluxInstance crd: allow insecure for oci sync

### ISSUE THREAD

**Issue by jazzlyn** [controlplaneio-fluxcd/flux-operator#81]
hi,
currently testing the flux operator with my local devenv and got this error.
```
failed to determine artifact digest: Get "https://home-ops-kind-registry:5000/v2/": http: server gave HTTP response to HTTPS client
```

would be great to allow `insecure` for oci in FluxInstance `.spec.sync`

f.e.
``` yaml
  sync:
    kind: OCIRepository
    url: oci://home-ops-kind-registry:5000/home-ops-devenv
    ref: local
    path: ./devenv/oci/flux
    insecure: true
```

**Comment by stefanprodan** [comment]
The `insecure` field is not common to all Flux sources, but you can set it via a kustomize patch like so:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
spec:
  kustomize:
    patches:
      - patch: |
          - op: add
            path: /spec/insecure
            value: true
        target:
          kind: (OCIRepository|Bucket)
```
