### ISSUE TITLE
Support sops decryption?

### ISSUE THREAD

**Issue by vicaya** [controlplaneio-fluxcd/flux-operator#92]
Existing fluxcd docs on sops requires adding a `decryption` configuration in `gotk-sync.yaml` for bootstrapped clusters. I don't see any docs on configuring decryption in FluxInstance.

Please clarify.

Thanks in advance!

**Comment by stefanprodan** [comment]
I've added an example here: https://fluxcd.control-plane.io/operator/flux-kustomize/#cluster-sync-sops-decryption

The enable decryption add the following patch to your FluxInstance:

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
spec:
  kustomize:
    patches:
      - patch: |
          - op: add
            path: /spec/decryption
            value:
              provider: sops
              secretRef:
                name: flux-sops
        target:
          kind: Kustomization
```

Make sure to create the SOPS secret in the flux-system namespace with the decryption keys before applying the FluxInstance.
